# HK NameSpace
apiVersion: v1
kind: Namespace
metadata:
  name: firestorm-hk
  labels:
    app: firestorm-hk
---
# Honk Kong Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hk-quote-deploy
  namespace: firestorm-hk
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  quote-hk
  template:
    metadata:
      labels:
        app: quote-hk
    spec:
      containers:
      - name: quote-hk-container
        image: aiadevopsaksacr.azurecr.io/quote-hk-image:latest
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: 500m
        env:
        - name:  NAME
          value: quote-hk
        ports:
        - containerPort: 8080
---
# Quote Service
apiVersion: v1
kind: Service 
metadata:
  name: quote-hk-svc
  namespace: firestorm-hk
spec:
  type: ClusterIP
  ports:
  - port: 8088
    targetPort: 8080
    protocol: TCP
  selector:
    app: quote-hk
---
# Product deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hk-product-deploy
  namespace: firestorm-hk
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  product-hk
  template:
    metadata:
      labels:
        app: product-hk
    spec:
      containers:
      - name: product-hk-container
        image: aiadevopsaksacr.azurecr.io/product-hk-image:latest
        env:
        - name:  NAME
          value: product-hk
        ports:
        - containerPort: 8080
---
# Product Service
apiVersion: v1
kind: Service
metadata:
  name: product-hk-svc
  namespace: firestorm-hk
spec:
  type: ClusterIP
  ports:
  - port: 8089
    targetPort: 8080
    protocol: TCP
  selector:
    app: product-hk
---
