apiVersion: v1
kind: Service
metadata:
  name: samplespringboot
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    run: samplespringboot
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: samplespringboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: samplespringboot
spec:
  selector:
    matchLabels:
      run: samplespringboot
  replicas: 1
  template:
    metadata:
      labels:
        run: samplespringboot
    spec:
      containers:
      - name: samplespringboot
        image: andrew/samplespringboot
        ports:
        - containerPort: 8080
